on: [push]

jobs:

  terrascan-docker:
    runs-on: ubuntu-latest
    name: terrascan-action-docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check out my policy repo
      uses: actions/checkout@main
      with:
        repository: igreenrajas/policy-as-a-code
        path: ./policy-as-a-code
    - name: Scan docker custom
      id: terrascan-k8s
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'docker'
        iac_version: 'v1'
        policy_type: 'docker'
        only_warn: true
        sarif_upload: true
        iac_dir: 'local-policy/'
        policy_path: 'policy-as-a-code/'
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
  
        
        
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action-terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check out my policy repo
      uses: actions/checkout@main
      with:
        repository: igreenrajas/policy-as-a-code
        path: ./policy-as-a-code  
    - name: Scan Terraform 
      id: terrascan
      uses:  tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'gcp'
        only_warn: true
        sarif_upload: true
        iac_dir: 'iac/gcp/'
        policy_path: 'policy-as-a-code/'
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: terrascan.sarif

  terrascan-k8s:
    runs-on: ubuntu-latest
    name: terrascan-action-k8s
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check out my policy repo
      uses: actions/checkout@main
      with:
        repository: igreenrajas/policy-as-a-code
        path: ./policy-as-a-code    
    - name: Scan k8s 
      id: terrascan-k8s
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        iac_version: 'v1'
        policy_type: 'k8s'
        only_warn: true
        sarif_upload: true
        iac_dir: 'k8s/sample-helm-docker2/kubeyaml/'
        policy_path: 'policy-as-a-code/'        
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: terrascan.sarif